### PR TITLE
Fireplace, 8 °C mode

### PR DESCRIPTION
**Pull request by juliekoubova**

### CODE REVIEW

**Comment by tetienne** [comment]
I was planning to implement the missing merits. But I'm glad you are taking care of it.

Did you know the Entity Description? IMO it fits perfectly with the merits and should ease your code.

You can see an exemple [here](https://github.com/home-assistant/core/blob/c0d0c89293df8e15b4288e0a4064291f77495aca/homeassistant/components/overkiz/switch.py) for the switch.

**Comment by juliekoubova** [comment]
That's a good suggestion, @tetienne, thanks! I'll see how the air purifier PR review goes, and will refactor this PR in the meantime :)

**Comment by h4de5** [comment]
looking forward to this. thank you very much!

**Comment by labr3y** [comment]
Hello,

I have an AC with several merit a & b features. If you need help with testing you can contact me, I'd be glad to help.

**merit_a_feature :** 
- CDU_SILENT_1
- CDU_SILENT_2
- ECO
- HIGH_POWER
- HEATING_8C

**merit_b_feature:** 
- FIREPLACE_1
- FIREPLACE_2

image


Model : RAS16J2AVSG-E1 + RAS B16N4VRG-E

**Comment by juliekoubova** [comment]
I'm abandoning this in favor of #124

**Pull request closed without merging**
