### PR TITLE
Fixed warning about supported features

### PR DESCRIPTION
**Pull request by albaintor**
Hi, as pointed out in https://github.com/h4de5/home-assistant-toshiba_ac/issues/187
I added missing features and methods.

Tested OK
Thanks

### CODE REVIEW

**Comment by h4de5** [comment]
might also
fixes #173

**Comment by h4de5** [comment]
unfortunatelly this does not solve the warning in the logs:

Entity None (<class 'custom_components.toshiba_ac.climate.ToshibaClimate'>) implements HVACMode(s): off, auto, cool, heat, dry, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/h4de5/home-assistant-toshiba_ac/issues

**Comment by albaintor** [comment]
Strange it solved on my side

**Comment by h4de5** [comment]
should be fixed now. see latest release https://github.com/h4de5/home-assistant-toshiba_ac/releases/tag/2024.6.1

**Comment by chrisandsally** [comment]
I get this error in logs after going to 2024.6.1
This error originated from a custom integration.

Logger: custom_components.toshiba_ac.climate
Source: custom_components/toshiba_ac/climate.py:57
integration: Toshiba AC (documentation, issues)
First occurred: 21:00:10 (1 occurrences)
Last logged: 21:00:10

Error during connection to Toshiba server 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://mobileapi.toshibahomeaccontrols.com/api/AC/GetCurrentACState?ACId=3e9fbd66-54ed-4bcf-a301-c84b4d855faa')

**Comment by h4de5** [comment]
try to reload the integration. just got this as well - it seems the API sometimes does not return valid data :\

**Comment by chrisandsally** [comment]
Reloaded and restarted and that messages cleared. Turned on and off air conditioner but get this now in logs

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:283
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:06:05 (1 occurrences)
Last logged: 21:06:05

[139813295328992] Preset mode is not valid. Valid preset modes are: Power 50, Power 75, Power 100

**Comment by h4de5** [comment]
what kind of preset modes does the App support on your device?

**Comment by chrisandsally** [comment]
Hi, it has a fan speed graph, not a numerical amount 50, 75, 100

see pic below. 
IMG_2811

**Comment by h4de5** [comment]
the preset modes are Power-Sel in the app. the icon suggests its also a three-level state.

the other thing is fan speed which is low, medium, medium-high, high, etc..

**Comment by h4de5** [comment]
just tested it through - cannot reproduce :(
```

2024-06-17 22:44:40.718 INFO (MainThread) [custom_components.toshiba_ac.climate] Toshiba Climate setting preset_mode: Power 50
2024-06-17 22:44:40.718 DEBUG (MainThread) [custom_components.toshiba_ac.feature_list] searching [<ToshibaAcPowerSelection.POWER_50: 1>, <ToshibaAcPowerSelection.POWER_75: 2>, <ToshibaAcPowerSelection.POWER_100: 3>, <ToshibaAcPowerSelection.NONE: None>] for Power 50
2024-06-17 22:44:40.718 DEBUG (MainThread) [custom_components.toshiba_ac.feature_list] and found [<ToshibaAcPowerSelection.POWER_50: 1>]
2024-06-17 22:45:26.439 INFO (MainThread) [custom_components.toshiba_ac.climate] Toshiba Climate setting preset_mode: Power 75
2024-06-17 22:45:26.439 DEBUG (MainThread) [custom_components.toshiba_ac.feature_list] searching [<ToshibaAcPowerSelection.POWER_50: 1>, <ToshibaAcPowerSelection.POWER_75: 2>, <ToshibaAcPowerSelection.POWER_100: 3>, <ToshibaAcPowerSelection.NONE: None>] for Power 75
2024-06-17 22:45:26.439 DEBUG (MainThread) [custom_components.toshiba_ac.feature_list] and found [<ToshibaAcPowerSelection.POWER_75: 2>]
2024-06-17 22:45:30.581 INFO (MainThread) [custom_components.toshiba_ac.climate] Toshiba Climate setting preset_mode: Power 100
2024-06-17 22:45:30.581 DEBUG (MainThread) [custom_components.toshiba_ac.feature_list] searching [<ToshibaAcPowerSelection.POWER_50: 1>, <ToshibaAcPowerSelection.POWER_75: 2>, <ToshibaAcPowerSelection.POWER_100: 3>, <ToshibaAcPowerSelection.NONE: None>] for Power 100
2024-06-17 22:45:30.581 DEBUG (MainThread) [custom_components.toshiba_ac.feature_list] and found [<ToshibaAcPowerSelection.POWER_100: 3>]
2024-06-17 22:45:50.933 INFO (MainThread) [custom_components.toshiba_ac.entity_description] AC device Klima calling set_ac_merit_a ECO
2024-06-17 22:45:58.055 INFO (MainThread) [custom_components.toshiba_ac.entity_description] AC device Klima calling set_ac_merit_a CDU_SILENT_1
2024-06-17 22:46:03.788 INFO (MainThread) [custom_components.toshiba_ac.entity_description] AC device Klima calling set_ac_merit_a CDU_SILENT_2
2024-06-17 22:46:28.923 INFO (MainThread) [custom_components.toshiba_ac.entity_description] AC device Klima calling set_ac_merit_a OFF
```

**Pull request merged**
