### PR TITLE
Add SAS token renewal

### PR DESCRIPTION
**Pull request by KaSroka**

### CODE REVIEW

**Comment by tux1980** [comment]
Thanks! But is not yet in the main branch, is it? Because HACS is not offering any updates to the Toshiba Integration right now.

**Comment by tux1980** [comment]
Are you going to merge it (different people had this issue I mean) or am I supposed to change my code in my HA manual? But next update will come and my added changes will be most likely overwritten afterwards.

**Comment by KaSroka** [comment]
It seems like you don't know how GitHub works, let me explain - @h4de5 is the owner of this repo and the only person with permissions to merge this (as of now).

**Comment by tux1980** [comment]
Sorry I thought you have the permissions to merge this repos. Ok, then I wait for an answer from @h4de5 
And no, I'm a bit familiar, I've been using GitHub for years now:)

**Comment by h4de5** [comment]
merged, release and tested. 

@KaSroka thanks, great work!

**Pull request merged**
