### PR TITLE
Allow energy consumption to be properly showed in HA Energy tab

### PR DESCRIPTION
**Pull request by KaSroka**
This requires latest HA (2021.9.0)

### CODE REVIEW

**Comment by h4de5** [comment]
did you try it with HA versions prior to the latest one?

**Comment by h4de5** [comment]
@h4de5 : we may have to adapt the minimum required version in hacs.json

**Comment by KaSroka** [comment]
It won't work with 2021.8.0 as in this version had `last_reset` which was deprecated in 2021.9.0 so I removed it already

**Comment by h4de5** [comment]
@KaSroka I added the last_reset property again - it should not break for newer versions, but can you check if it still works correctly?

**Comment by h4de5** [comment]
also please have a look at the logs and search for:
```[custom_components.toshiba_ac.sensor] energy_consumption ..```
to see if the energy_consumption member is set at this state. this would make it easy to only add it based on capabilities.

**Comment by KaSroka** [comment]
I don't think we need this as:
- it generates deprecation warnings in 2021.9.0
- `STATE_CLASS_TOTAL_INCREASING` was added in 2021.9.0 so we cannot use this in older versions anyway

**Comment by KaSroka** [comment]
Taking into account my last point I think that we should remove `last_reset` and set minimal version to `2021.9.0`

**Comment by KaSroka** [comment]
@h4de5 Taking into account my last point I think that we should remove last_reset and set minimal version to 2021.9.0

**Pull request merged**
