### PR TITLE
Call async_forward_entry_setups

### LINKED ISSUE #106: Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3.
Running HA Home Assistant 2023.2.0 : From my  logg:

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for toshiba_ac using this method at custom_components/toshiba_ac/__init__.py, line 45: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

### PR DESCRIPTION
**Pull request by tetienne**
Fix #106

### CODE REVIEW

**Comment by tetienne** [comment]
@h4de5 can I have your review please?

**Comment by h4de5** [comment]
@tetienne why was the black linting removed?

**Comment by tetienne** [comment]
Black is included within the pre-commit workflow, it was duplicated.

**Comment by h4de5** [comment]
ah. it is defined in `.pre-commit-config.yaml`
one day I am gonna learn how this stuff is connected..

**Comment by tetienne** [comment]
@h4de5 don't hesitate to contact me on Discord if you want some explanations.

**Pull request merged**
