### PR TITLE
Remove inaccurate hvac_action

### LINKED ISSUE #77: AC telling "inactive" while it's working when temperature Is as set point
> Here everything is back working with 2022.7.1. This morning wasn't.
> 
> The only thing I noticed Is AC telling "inactive" while it's working when temperature Is as set point, not working like this before

thats right. this is something that was not release before. I tested some stuff, it should return idle state, so you can check in automations for this. as the AC unit does not go into idle mode, this does not reflect reality. Ill create a new issue for this.

_Originally posted by @h4de5 in https://github.com/h4de5/home-assistant-toshiba_ac/issues/72#issuecomment-1189230469_

### PR DESCRIPTION
**Pull request by tetienne**
Fix #77 and #55

As discussed, we should not report something not reported by the Toshiba API.

### CODE REVIEW

**Comment by h4de5** [comment]
why remove all of the hvac action? as I understood the api will return what we want - https://github.com/KaSroka/Toshiba-AC-control/issues/31#issuecomment-1188140789

its just the check for of current temperature and the idle should be removed.

**Comment by tetienne** [comment]
From @KaSroka comment, it's not possible to retrieve the current running action from the API. If you enable the heating mode, the API does not tell you if you are actually heating or not.

It's why I removed the whole hvac_action.

**Comment by KaSroka** [comment]
I agree, this should be removed. Especially that new AC units are not idle when they reach set temperature, they just reduce power to keep requested temperature without switching itself on/off. So they are never really idle.

**Comment by tetienne** [comment]
@KaSroka You agreed about removing the whole action or the idle part?

**Comment by KaSroka** [comment]
Whole action part

**Pull request merged**
